# Site settings
title: Pessiml
email: enquiries@pessim.al
url: https://example.github.io
description: "The worse things get, the more money you make!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Pessiml

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty
